### ISSUE TITLE
resolvers only for "Root*"? Not for schemas?

### ISSUE THREAD

**Issue by dylang** [lucasconstantino/graphql-modules#2]
In this code:
```js
const resolvers = {
    ...(queries ? { RootQuery: queriesResolvers } : {}),
    ...(mutations ? { RootMutation: mutationsResolvers } : {}),
    ...(subscriptions ? { RootSubscription: subscriptionsResolvers } : {}),
  }
```

It seems like all resolvers _must_ be defined under "RootQuery". This means I need to set the root `query` key to `"RootQuery"`, etc.

Is it not possible to define top-level resolvers for top-level types?

I'm still learning graphql, so I may not be understanding all of the concepts.

The error I'm getting:

```
Error: RootQuery.Users defined in resolvers, but not in schema
```

`type Users` is in the schema, but it's not a query.

**Comment by lucasconstantino** [comment]
As far as I understand it, graphql accepts only one root query, one root mutation, and one root subscription. In `graphql-modules`, the key for these queries can be modified as follows:

```js
  bundle(modules, {
    rootKeys: {
      query: 'CustomRootQuery'
    }
  })
```

About the field resolvers (as for how [makeExecutableSchema](https://github.com/apollostack/graphql-tools) expects), this is indeed something that is missing in my code. I guess we can simply read the other keys in the resolver map and add them as is. Do you think you can do it in a pull-request? If not so, I'll work on something that needs it this on monday, so I'll probably solve this by then.

Thanks for reporting ;)

**Comment by dylang** [comment]
Works great, thank you!
