### ISSUE TITLE
Add a recipe on how to use this with FeathersJS

### ISSUE THREAD

**Issue by jay-jlm** [lucasconstantino/graphql-modules#5]
With Feathers the resolver is defined inside of a function like in this example:
https://github.com/benawad/taco-apollo/blob/master/src/services/graphql/resolvers.js

which is then invoked on to  scope of the application like this:
`Resolvers.call(app)` 

So it's not immediately clear if this package can be used with Feathers.

**Comment by lucasconstantino** [comment]
I had a look at *taco-apollo* and I think I understand how you can use *graphql-modules* in your project:

First, keep in mind that *graphql-modules* is just a helper to allow for modularized way to build the *typeDefs* and *resolvers* as required by the *[makeExecutableSchema](https://github.com/benawad/taco-apollo/blob/master/src/services/graphql/index.js#L12)* function.

Having that said, prior to calling this method you could do as wish to build the bundle using *graphql-modules*

But I think the major issue here is: you are trying to have access to contextualized things such as `app.service('tacos')` on the resolvers, but you are missing the fact that you could provide access to this `app` thing using the context you [already have](https://github.com/benawad/taco-apollo/blob/master/src/services/graphql/index.js#L21). Just pass `app` down to the resolvers using this context, and get the desired service on each resolver function.

If you follow this road, there will be no need for the *Resolver* file to export a function anymore.
