### ISSUE TITLE
Adding type definitions that need to be shared between modules

### ISSUE THREAD

**Issue by jay-at-avido** [lucasconstantino/graphql-modules#6]
A common scenario is to have some base graphql type definitions such Author or EmailAccount  which are not associated with any specific module because they are used in more than one module.

I'm not sure that's currently an obvious/straightforward way to integrate those with the modules system

**Comment by lucasconstantino** [comment]
You could have a module called *core*. You could have a module called *accounts*. Whatever you like. You can they either add them directly to the bundling or add them as dependencies inside the other modules of your application. Does it clarify something for you?

I've been using `graphql-modules` in all my projects, and for sure it lacks a couple o things. But in the end it simply consists `typeDefs` and `resolvers` as expected by `makeExecutableSchema`, so the problems I face are most often problems that would occur had I not used `graphql-modules`.

**Comment by giautm** [comment]
Liked. I make a module called `core` to add scalar types:
```
import GraphQLJSON from 'graphql-type-json';
import {
  GraphQLDate,
  GraphQLTime,
  GraphQLDateTime,
} from 'graphql-iso-date';

export default () => ({
  schema: `
    scalar JSON
    scalar Date
    scalar Time
    scalar DateTime
  `,
  resolvers: {
    JSON: GraphQLJSON,
    Date: GraphQLDate,
    Time: GraphQLTime,
    DateTime: GraphQLDateTime,
  },
});
```
